title: CONFEST 2024
description: Include four conferences
theme: just-the-docs

url: https://ss-beri.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
